spring:
  application:
    name: ToyProject
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prd}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email


server:
  port: 3000

logging:
  level:
    org.springframework.web.socket: TRACE
    org.springframework.messaging: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  access-secret: ${ACCESS_JWT_SECRET}
  refresh-secret: ${REFRESH_JWT_SECRET}
  token-validity-in-seconds: 3600