spring:
  application:
    name: ToyProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none  # ?? create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL 8? ??
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2.0_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2.0_GOOGLE_CLIENT_SECRET}
            scope:
              - email
  config:
    import: optional:file:.env[.properties]
server:
  port: 3000


